return {
  'akinsho/bufferline.nvim',
  version = "*",
  dependencies = 'nvim-tree/nvim-web-devicons',
  keys = {
    { '<A-,>',     '<Cmd>BufferPrevious<CR>',            desc = 'Go to previous buffer' },
    { '<A-.>',     '<Cmd>BufferNext<CR>',                desc = 'Go to next buffer' },
    { '<A-<>',     '<Cmd>BufferMovePrevious<CR>',        desc = 'Move buffer to previous position' },
    { '<A->>',     '<Cmd>BufferMoveNext<CR>',            desc = 'Move buffer to next position' },
    { '<A-1>',     '<Cmd>BufferGoto 1<CR>',              desc = 'Go to buffer 1' },
    { '<A-2>',     '<Cmd>BufferGoto 2<CR>',              desc = 'Go to buffer 2' },
    { '<A-3>',     '<Cmd>BufferGoto 3<CR>',              desc = 'Go to buffer 3' },
    { '<A-4>',     '<Cmd>BufferGoto 4<CR>',              desc = 'Go to buffer 4' },
    { '<A-5>',     '<Cmd>BufferGoto 5<CR>',              desc = 'Go to buffer 5' },
    { '<A-6>',     '<Cmd>BufferGoto 6<CR>',              desc = 'Go to buffer 6' },
    { '<A-7>',     '<Cmd>BufferGoto 7<CR>',              desc = 'Go to buffer 7' },
    { '<A-8>',     '<Cmd>BufferGoto 8<CR>',              desc = 'Go to buffer 8' },
    { '<A-9>',     '<Cmd>BufferGoto 9<CR>',              desc = 'Go to buffer 9' },
    { '<A-0>',     '<Cmd>BufferLast<CR>',                desc = 'Go to last buffer' },
    { '<A-p>',     '<Cmd>BufferPin<CR>',                 desc = 'Pin/unpin buffer' },
    { '<A-c>',     '<Cmd>BufferClose<CR>',               desc = 'Close buffer' },
    { '<C-p>',     '<Cmd>BufferPick<CR>',                desc = 'Magic buffer-picking mode' },
    { '<Space>bb', '<Cmd>BufferOrderByBufferNumber<CR>', desc = 'Sort by buffer number' },
    { '<Space>bd', '<Cmd>BufferOrderByDirectory<CR>',    desc = 'Sort by directory' },
    { '<Space>bl', '<Cmd>BufferOrderByLanguage<CR>',     desc = 'Sort by language' },
    { '<Space>bn', '<Cmd>BufferOrderByName<CR>',         desc = 'Sort by name' },
    { '<Space>bw', '<Cmd>BufferOrderByWindowNumber<CR>', desc = 'Sort by window number' },
  },
}
